services:
  postgres:
    image: postgres:15
    container_name: reactivities_postgres
    environment:
      POSTGRES_USER: react_user
      POSTGRES_PASSWORD: react_password
      POSTGRES_DB: react_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
